Добавить первую строку песни
RoSMag/22ip1-2-23ipp pull request #1
Opened 2024-10-09 09:32 UTC by LiChanDez

2024-10-09 09:33 UTC, RoSMag requested changes
Это текст песни, не надо заголовок.
в последнем слове опечатка.

2024-10-11 05:55 UTC, LiChanDez commented
Исправил ошибки в коммите 66e6940f292ee76a9657b92b3964359886a258a0

2024-10-11 06:02 UTC, RoSMag requested changes
Я неправильно сформулировал.
Заголовок с названием песенки надо оставить. Не нужно оформлять саму песню как заголовок.

2024-10-11 06:11 UTC, LiChanDez commented
Вернул заголовок в коммите 80fe038f2f1cf04fb9fd6e1319093e972a980fce

2024-10-11 06:12 UTC, RoSMag approved these changes
ok

2024-10-11 06:13 UTC, merged