Добавил строчку с ошибкой
RoSMag/22ip1-2-23ipp pull request #43
Opened 2024-12-06 14:07 UTC by Weyvi

2024-12-06 14:14 UTC, LaziestAvali requested changes
Чуть больше чем надо, сделай только 1 строку

2024-12-06 14:17 UTC, RoSMag requested changes
1. это не тот абзац. песня уже дальше ушла.
2. Надо одну строку добавлять. Там предыдущие ошибочно переход на новую строку забыли поставить. два раза.

2024-12-06 14:28 UTC, LaziestAvali requested changes
Последняя фраза 2 раза повторяется.

2024-12-06 14:32 UTC, LaziestAvali approved these changes
Вроде норм

2024-12-10 11:34 UTC, RoSMag approved these changes
ок

2024-12-10 11:34 UTC, merged